### ISSUE TITLE
Modify elbow limit switch logic

### ISSUE THREAD

**Issue by kalee1** [kalee1/ftc_app_8668_RoverRuckus#13]
Right now, the elbow limit switches are checked one right after the other with 2 if-else structures:
```
   if (elbowBack != null)
   {
        if (elbowBack.getValue() != 1)
        {
            elbow.setPower(-0.5);
        }
        else
        {
            elbow.setPower(RightStickY);
        }
    }
    if (elbowFront != null)
    {
        if (elbowFront.isPressed())
        {
            elbow.setPower(0.5);
        }
        else
        {
            elbow.setPower(RightStickY);
        }
    }
```
This results in the `elbow.setPower()` being called twice, once in each limit switch check.  We want to command a motor to a specific power once per loop.  Therefore, modify the `if-else` structure to be `if-elseif-else` where one limit switch is checked in the `if` case, the 2nd limit switch is checked in the `elseif` case, and the normal power is set in the `else` case.  Something like:
```
if ( back limit switch is not null AND is pressed )
{
    set the elbow power to -0.5;
}
else if ( front limit switch is not null AND is pressed )
{
    set the elbow power to 0.5;
}
else
{
    set the elbow power to RightStickY;
}
```
This will result in `elbow.setPower()` being called once.

**Comment by DeathJester1513** [comment]
Fixed the Issue in Ben_Autonomous & Feature_Motor-arm
