### ISSUE TITLE
Begin using "Home" in describing arm motions that deal with the arm fully retracted

### ISSUE THREAD

**Issue by kalee1** [kalee1/ftc_app_8668_RoverRuckus#16]
It's common in motor control to call your initial, zero position "Home".  Since the variables, `elbowStart` and `shoulderStart` are intended to be the positions for the arm when it is fully retracted, these variables are its home positions.  Rename them `elbowHomePos` and `shoulderHomePos` or something similar.  

Similarly, the `armRetract(boolean elbowFirst)` method is used to return the arm to its home position.  It makes sense to rename that method `armHome(boolean elbowFirst)` or something similar.

**Comment by DeathJester1513** [comment]
Fixed naming in feature_MotorArm
